import { useEffect, useState } from 'react'
import { collection, query, where, getDocs, setDoc, doc, serverTimestamp, addDoc } from 'firebase/firestore'
import { db } from '@shared/lib/firebase'
import Typography from '@mui/material/Typography'
import Box from '@mui/material/Box'
import Button from '@mui/material/Button'
import Select from '@mui/material/Select'
import MenuItem from '@mui/material/MenuItem'
import FormControl from '@mui/material/FormControl'
import InputLabel from '@mui/material/InputLabel'
import CircularProgress from '@mui/material/CircularProgress'
import Alert from '@mui/material/Alert'
import Dialog from '@mui/material/Dialog'
import DialogTitle from '@mui/material/DialogTitle'
import DialogContent from '@mui/material/DialogContent'
import DialogActions from '@mui/material/DialogActions'
import TextField from '@mui/material/TextField'
import Checkbox from '@mui/material/Checkbox'
import FormControlLabel from '@mui/material/FormControlLabel'

export default function AdminStaffBasic({ schoolId, assignmentYear }) {
  const [loading, setLoading] = useState(true)
  const [assignmentRows, setAssignmentRows] = useState([])
  const [editingAssignment, setEditingAssignment] = useState(null)
  const [savingAssignment, setSavingAssignment] = useState(false)

  // 일괄 수정
  const [selectedUids, setSelectedUids] = useState(new Set())
  const [bulkEditOpen, setBulkEditOpen] = useState(false)
  const [bulkFields, setBulkFields] = useState(null)
  const [savingBulk, setSavingBulk] = useState(false)

  // CSV 업로드
  const [assignParsedRows, setAssignParsedRows] = useState([])
  const [assignUploadMsg, setAssignUploadMsg] = useState('')
  const [savingAssignUpload, setSavingAssignUpload] = useState(false)

  useEffect(() => {
    if (!schoolId) return
    fetchAssignments()
  }, [schoolId, assignmentYear])

  const fetchAssignments = async () => {
    if (!schoolId) return
    setLoading(true)
    try {
      const [usersSnap, assignSnap] = await Promise.all([
        getDocs(query(
          collection(db, 'users'),
          where('schoolId', '==', schoolId),
          where('role', 'in', ['teacher', 'admin', 'school_admin', 'principal']),
        )),
        getDocs(query(
          collection(db, 'schools', schoolId, 'teacherAssignments'),
          where('year', '==', assignmentYear),
        )),
      ])
    const assignByUid = {}
    assignSnap.docs.forEach(d => { assignByUid[d.data().uid] = { id: d.id, ...d.data() } })

      const rows = usersSnap.docs
        .map(d => ({ id: d.id, ...d.data() }))
        .map(u => ({ uid: u.id, name: u.name, email: u.email, staffType: u.staffType, assignment: assignByUid[u.id] || null }))
        .sort((a, b) => (a.name || '').localeCompare(b.name || '', 'ko'))

      setAssignmentRows(rows)

      // 자동으로 "전체 교직원" 연수 프리셋 생성/업데이트
      if (rows.length > 0) {
        const allMembers = rows.map(row => ({
          uid: row.uid,
          name: row.name,
          email: row.email,
          staffType: '교직원'
        }))

        // 기존 "전체 교직원" 프리셋 확인
        const presetsSnap = await getDocs(query(
          collection(db, 'schools', schoolId, 'trainingPresets'),
          where('autoGenerated', '==', true),
          where('year', '==', assignmentYear)
        ))

        const existingPreset = presetsSnap.docs.find(d => d.data().name === `전체 교직원 (${assignmentYear})`)

        if (existingPreset) {
          // 업데이트
          await setDoc(doc(db, 'schools', schoolId, 'trainingPresets', existingPreset.id), {
            name: `전체 교직원 (${assignmentYear})`,
            members: allMembers,
            autoGenerated: true,
            year: assignmentYear,
            updatedAt: serverTimestamp()
          })
        } else {
          // 생성
          await addDoc(collection(db, 'schools', schoolId, 'trainingPresets'), {
            name: `전체 교직원 (${assignmentYear})`,
            members: allMembers,
            autoGenerated: true,
            year: assignmentYear,
            createdAt: serverTimestamp()
          })
        }
      }
    } catch (err) {
      console.error('교직원 배정 로딩 실패:', err)
    } finally {
      setLoading(false)
    }
  }

  const openAssignmentModal = (row) => {
    const a = row.assignment || {}
    setEditingAssignment({
      uid: row.uid,
      name: row.name,
      department: a.department || '',
      subject: a.subject || '',
      isHomeroom: a.isHomeroom || false,
      homeroomGrade: a.homeroomGrade || '',
      homeroomClassNo: a.homeroomClassNo || '',
      office: a.office || '',
      positionLabel: a.positionLabel || '',
    })
  }

  const saveAssignment = async () => {
    if (!editingAssignment) return
    setSavingAssignment(true)
    try {
      const { uid, name, homeroomGrade, homeroomClassNo, ...form } = editingAssignment
      const docId = `${assignmentYear}_${uid}`
      await setDoc(doc(db, 'schools', schoolId, 'teacherAssignments', docId), {
        uid,
        year: assignmentYear,
        ...form,
        homeroomGrade: form.isHomeroom && homeroomGrade ? Number(homeroomGrade) : null,
        homeroomClassNo: form.isHomeroom && homeroomClassNo ? Number(homeroomClassNo) : null,
        updatedAt: serverTimestamp(),
      }, { merge: true })
      setEditingAssignment(null)
      await fetchAssignments()
    } catch (err) {
      alert('저장 실패: ' + err.message)
    } finally {
      setSavingAssignment(false)
    }
  }

  const toggleSelectUid = (uid) => {
    setSelectedUids(prev => {
      const next = new Set(prev)
      next.has(uid) ? next.delete(uid) : next.add(uid)
      return next
    })
  }

  const toggleSelectAllAssignments = () => {
    setSelectedUids(prev =>
      prev.size === assignmentRows.length ? new Set() : new Set(assignmentRows.map(r => r.uid))
    )
  }

  const openBulkEdit = () => {
    setBulkFields({
      positionLabel: { on: false, value: '' },
      department: { on: false, value: '' },
      subject: { on: false, value: '' },
      office: { on: false, value: '' },
      homeroom: { on: false, isHomeroom: false, grade: '', classNo: '' },
    })
    setBulkEditOpen(true)
  }

  const saveBulkEdit = async () => {
    if (!bulkFields) return
    setSavingBulk(true)
    try {
      const payload = { updatedAt: serverTimestamp() }
      if (bulkFields.positionLabel.on) payload.positionLabel = bulkFields.positionLabel.value
      if (bulkFields.department.on) payload.department = bulkFields.department.value
      if (bulkFields.subject.on) payload.subject = bulkFields.subject.value
      if (bulkFields.office.on) payload.office = bulkFields.office.value
      if (bulkFields.homeroom.on) {
        payload.isHomeroom = bulkFields.homeroom.isHomeroom
        payload.homeroomGrade = bulkFields.homeroom.isHomeroom && bulkFields.homeroom.grade ? Number(bulkFields.homeroom.grade) : null
        payload.homeroomClassNo = bulkFields.homeroom.isHomeroom && bulkFields.homeroom.classNo ? Number(bulkFields.homeroom.classNo) : null
      }
      await Promise.all([...selectedUids].map(uid =>
        setDoc(doc(db, 'schools', schoolId, 'teacherAssignments', `${assignmentYear}_${uid}`), {
          uid, year: assignmentYear, ...payload,
        }, { merge: true })
      ))
      setBulkEditOpen(false)
      setSelectedUids(new Set())
      await fetchAssignments()
    } catch (err) {
      alert('일괄 저장 실패: ' + err.message)
    } finally {
      setSavingBulk(false)
    }
  }

  // CSV 관련 함수들
  const csvCell = (v) => {
    const s = (v ?? '').toString()
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
  }

  const downloadAssignmentCsv = () => {
    const header = ['이메일', '이름', '직함', '부서', '담당교과', '담임학년', '담임반', '사무실']
    const rows = assignmentRows.map(row => {
      const a = row.assignment || {}
      return [
        row.email || '',
        row.name || '',
        a.positionLabel || '',
        a.department || '',
        a.subject || '',
        a.isHomeroom && a.homeroomGrade ? a.homeroomGrade : '',
        a.isHomeroom && a.homeroomClassNo ? a.homeroomClassNo : '',
        a.office || '',
      ].map(csvCell).join(',')
    })
    const csv = [header.join(','), ...rows].join('\n')
    const blob = new Blob(['﻿' + csv], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `교원배정_${assignmentYear}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  const parseAssignmentRows = (text) => {
    const lines = text.trim().split(/\r?\n/)
    if (lines.length < 2) return null
    const delim = lines[0].includes('\t') ? '\t' : ','
    const headers = lines[0].split(delim).map(h => h.trim().toLowerCase())
    const findIdx = (names) => headers.findIndex(h => names.includes(h))
    const emailIdx = findIdx(['이메일', 'email'])
    if (emailIdx === -1) return null
    const positionIdx = findIdx(['직함', 'position'])
    const deptIdx = findIdx(['부서', 'department'])
    const subjectIdx = findIdx(['담당교과', '과목', 'subject'])
    const gradeIdx = findIdx(['담임학년', '학년'])
    const classIdx = findIdx(['담임반', '반'])
    const officeIdx = findIdx(['사무실', 'office'])

    return lines.slice(1).map(line => {
      const cols = line.split(delim).map(v => v.trim())
      const grade = gradeIdx !== -1 ? cols[gradeIdx] : ''
      const classNo = classIdx !== -1 ? cols[classIdx] : ''
      return {
        email: (cols[emailIdx] || '').toLowerCase(),
        positionLabel: positionIdx !== -1 ? cols[positionIdx] || '' : '',
        department: deptIdx !== -1 ? cols[deptIdx] || '' : '',
        subject: subjectIdx !== -1 ? cols[subjectIdx] || '' : '',
        isHomeroom: !!(grade && classNo),
        homeroomGrade: grade ? Number(grade) : null,
        homeroomClassNo: classNo ? Number(classNo) : null,
        office: officeIdx !== -1 ? cols[officeIdx] || '' : '',
      }
    }).filter(r => r.email && r.email.includes('@'))
  }

  const handleAssignCsvUpload = async (e) => {
    const file = e.target.files?.[0]
    if (!file) return
    e.target.value = ''
    try {
      const text = await file.text()
      const rows = parseAssignmentRows(text)
      if (!rows) { setAssignUploadMsg('CSV 헤더에 "이메일" 열이 필요합니다.'); return }
      if (rows.length === 0) { setAssignUploadMsg('유효한 데이터가 없습니다.'); return }
      setAssignParsedRows(rows)
      setAssignUploadMsg('')
    } catch (err) {
      setAssignUploadMsg('파일 읽기 실패: ' + err.message)
    }
  }

  const handleSaveAssignUpload = async () => {
    if (assignParsedRows.length === 0) return
    setSavingAssignUpload(true)
    setAssignUploadMsg('')
    try {
      const emailToUid = {}
      assignmentRows.forEach(r => { if (r.email) emailToUid[r.email.toLowerCase()] = r.uid })

      let matched = 0
      let unmatched = 0
      await Promise.all(assignParsedRows.map(async (row) => {
        const uid = emailToUid[row.email]
        if (!uid) { unmatched++; return }
        matched++
        const { email, ...form } = row
        await setDoc(doc(db, 'schools', schoolId, 'teacherAssignments', `${assignmentYear}_${uid}`), {
          uid, year: assignmentYear, ...form, updatedAt: serverTimestamp(),
        }, { merge: true })
      }))

      setAssignUploadMsg(`✅ ${matched}명 반영 완료${unmatched > 0 ? ` · 매칭 안 된 이메일 ${unmatched}건 (구성원 목록에 없는 이메일)` : ''}`)
      setAssignParsedRows([])
      await fetchAssignments()
    } catch (err) {
      setAssignUploadMsg('저장 실패: ' + err.message)
    } finally {
      setSavingAssignUpload(false)
    }
  }

  return (
    <Box>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 3, flexWrap: 'wrap' }}>
        {selectedUids.size > 0 && (
          <Button variant="contained" color="secondary" onClick={openBulkEdit}>
            선택 {selectedUids.size}명 일괄 수정
          </Button>
        )}
      </Box>

      {loading ? (
        <Box display="flex" justifyContent="center" alignItems="center" minHeight="200px">
          <CircularProgress />
        </Box>
      ) : assignmentRows.length === 0 ? (
        <Typography color="text.secondary">소속 교직원이 없습니다.</Typography>
      ) : (
        <Box sx={{ overflowX: 'auto' }}>
          <table style={styles.table}>
            <thead>
              <tr>
                <th style={styles.th}>
                  <input
                    type="checkbox"
                    checked={selectedUids.size === assignmentRows.length}
                    onChange={toggleSelectAllAssignments}
                  />
                </th>
                <th style={styles.th}>이름</th>
                <th style={styles.th}>직함</th>
                <th style={styles.th}>부서</th>
                <th style={styles.th}>담당 교과</th>
                <th style={styles.th}>담임</th>
                <th style={styles.th}>사무실</th>
                <th style={styles.th}>수정</th>
              </tr>
            </thead>
            <tbody>
              {assignmentRows.map(row => {
                const a = row.assignment
                return (
                  <tr key={row.uid}>
                    <td style={styles.td}>
                      <input
                        type="checkbox"
                        checked={selectedUids.has(row.uid)}
                        onChange={() => toggleSelectUid(row.uid)}
                      />
                    </td>
                    <td style={styles.td}>{row.name || '—'}</td>
                    <td style={styles.td}>{a?.positionLabel || '—'}</td>
                    <td style={styles.td}>{a?.department || '—'}</td>
                    <td style={styles.td}>{a?.subject || '—'}</td>
                    <td style={styles.td}>{a?.isHomeroom ? `${a.homeroomGrade || ''}학년 ${a.homeroomClassNo || ''}반` : '—'}</td>
                    <td style={styles.td}>{a?.office || '—'}</td>
                    <td style={styles.td}>
                      <button onClick={() => openAssignmentModal(row)} style={styles.approveBtn}>배정 수정</button>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </Box>
      )}

      {/* 일괄 업로드 섹션 */}
      <Box sx={{ mt: 4, pt: 3, borderTop: '1px solid #e0e0e0' }}>
        <Typography variant="h6" fontWeight={600} mb={1}>
          일괄 업로드
        </Typography>
        <Typography variant="body2" color="text.secondary" mb={2}>
          1) 현재 명단을 CSV로 받아서 엑셀로 채운 뒤 2) 다시 올리면 반영됩니다. <strong>이메일</strong> 열로 구성원 목록과 매칭합니다.
        </Typography>

        <Box sx={{ display: 'flex', gap: 2, mb: 2, flexWrap: 'wrap' }}>
          <Button variant="outlined" onClick={downloadAssignmentCsv}>
            현재 명단 CSV 다운로드 ({assignmentYear})
          </Button>
          <Button variant="outlined" component="label">
            채운 CSV 업로드
            <input type="file" accept=".csv" hidden onChange={handleAssignCsvUpload} />
          </Button>
        </Box>

        {assignParsedRows.length > 0 && (
          <Box sx={{ mb: 2 }}>
            <Typography variant="body2" mb={1}>
              {assignParsedRows.length}건 확인됨 — 저장하면 즉시 반영됩니다.
            </Typography>
            <Box sx={{ overflowX: 'auto', maxHeight: 300, overflow: 'auto' }}>
              <table style={styles.table}>
                <thead>
                  <tr>
                    <th style={styles.th}>이메일</th>
                    <th style={styles.th}>직함</th>
                    <th style={styles.th}>부서</th>
                    <th style={styles.th}>담당교과</th>
                    <th style={styles.th}>담임</th>
                    <th style={styles.th}>사무실</th>
                  </tr>
                </thead>
                <tbody>
                  {assignParsedRows.map((r, i) => (
                    <tr key={i}>
                      <td style={styles.td}>{r.email}</td>
                      <td style={styles.td}>{r.positionLabel || '—'}</td>
                      <td style={styles.td}>{r.department || '—'}</td>
                      <td style={styles.td}>{r.subject || '—'}</td>
                      <td style={styles.td}>{r.isHomeroom ? `${r.homeroomGrade}학년 ${r.homeroomClassNo}반` : '—'}</td>
                      <td style={styles.td}>{r.office || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </Box>
            <Button
              variant="contained"
              onClick={handleSaveAssignUpload}
              disabled={savingAssignUpload}
              sx={{ mt: 1 }}
            >
              {savingAssignUpload ? '저장 중...' : `${assignParsedRows.length}건 저장`}
            </Button>
          </Box>
        )}

        {assignUploadMsg && (
          <Alert severity={assignUploadMsg.includes('✅') ? 'success' : 'error'} sx={{ mt: 2 }}>
            {assignUploadMsg}
          </Alert>
        )}
      </Box>

      {/* 개별 배정 수정 모달 */}
      <Dialog open={!!editingAssignment} onClose={() => setEditingAssignment(null)} maxWidth="sm" fullWidth>
        <DialogTitle>
          {editingAssignment?.name} — 배정 정보 ({assignmentYear})
        </DialogTitle>
        <DialogContent>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: 1 }}>
            <TextField
              label="직함"
              value={editingAssignment?.positionLabel || ''}
              onChange={e => setEditingAssignment(prev => ({ ...prev, positionLabel: e.target.value }))}
              placeholder="예: 교무부장"
              fullWidth
            />
            <TextField
              label="부서"
              value={editingAssignment?.department || ''}
              onChange={e => setEditingAssignment(prev => ({ ...prev, department: e.target.value }))}
              placeholder="예: 교무부"
              fullWidth
            />
            <TextField
              label="담당 교과"
              value={editingAssignment?.subject || ''}
              onChange={e => setEditingAssignment(prev => ({ ...prev, subject: e.target.value }))}
              placeholder="예: 수학"
              fullWidth
            />

            <FormControlLabel
              control={
                <Checkbox
                  checked={editingAssignment?.isHomeroom || false}
                  onChange={e => setEditingAssignment(prev => ({ ...prev, isHomeroom: e.target.checked }))}
                />
              }
              label="담임"
            />

            {editingAssignment?.isHomeroom && (
              <Box sx={{ display: 'flex', gap: 2 }}>
                <FormControl fullWidth>
                  <InputLabel>담임 학년</InputLabel>
                  <Select
                    value={editingAssignment?.homeroomGrade || ''}
                    label="담임 학년"
                    onChange={e => setEditingAssignment(prev => ({ ...prev, homeroomGrade: e.target.value }))}
                  >
                    <MenuItem value="">선택</MenuItem>
                    <MenuItem value="1">1학년</MenuItem>
                    <MenuItem value="2">2학년</MenuItem>
                    <MenuItem value="3">3학년</MenuItem>
                  </Select>
                </FormControl>
                <TextField
                  label="담임 반"
                  value={editingAssignment?.homeroomClassNo || ''}
                  onChange={e => setEditingAssignment(prev => ({ ...prev, homeroomClassNo: e.target.value }))}
                  placeholder="예: 3"
                  fullWidth
                />
              </Box>
            )}

            <TextField
              label="사무실"
              value={editingAssignment?.office || ''}
              onChange={e => setEditingAssignment(prev => ({ ...prev, office: e.target.value }))}
              placeholder="예: 교무실"
              fullWidth
              helperText="실제 자리 배치(좌석 위치)는 공간 관리 탭에서 별도로 관리합니다"
            />
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setEditingAssignment(null)}>취소</Button>
          <Button onClick={saveAssignment} disabled={savingAssignment} variant="contained">
            {savingAssignment ? '저장 중...' : '저장'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* 일괄 수정 모달 */}
      <Dialog open={bulkEditOpen} onClose={() => setBulkEditOpen(false)} maxWidth="sm" fullWidth>
        <DialogTitle>
          {selectedUids.size}명 일괄 수정 ({assignmentYear})
        </DialogTitle>
        <DialogContent>
          <Typography variant="caption" color="text.secondary" sx={{ mb: 2, display: 'block' }}>
            체크한 항목만 선택된 교원 전체에 적용됩니다. 체크 안 한 항목은 각자 기존 값 유지.
          </Typography>

          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: 1 }}>
            {[
              { key: 'positionLabel', label: '직함', placeholder: '예: 교무부장' },
              { key: 'department', label: '부서', placeholder: '예: 교무부' },
              { key: 'subject', label: '담당 교과', placeholder: '예: 수학' },
              { key: 'office', label: '사무실', placeholder: '예: 교무실' },
            ].map(f => (
              <Box key={f.key} sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <Checkbox
                  checked={bulkFields?.[f.key]?.on || false}
                  onChange={e => setBulkFields(prev => ({ ...prev, [f.key]: { ...prev[f.key], on: e.target.checked } }))}
                />
                <TextField
                  label={f.label}
                  value={bulkFields?.[f.key]?.value || ''}
                  onChange={e => setBulkFields(prev => ({ ...prev, [f.key]: { ...prev[f.key], value: e.target.value } }))}
                  placeholder={f.placeholder}
                  disabled={!bulkFields?.[f.key]?.on}
                  fullWidth
                  size="small"
                />
              </Box>
            ))}

            <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 1 }}>
              <Checkbox
                checked={bulkFields?.homeroom?.on || false}
                onChange={e => setBulkFields(prev => ({ ...prev, homeroom: { ...prev.homeroom, on: e.target.checked } }))}
                sx={{ mt: 0.5 }}
              />
              <Box sx={{ flex: 1 }}>
                <FormControlLabel
                  control={
                    <Checkbox
                      checked={bulkFields?.homeroom?.isHomeroom || false}
                      disabled={!bulkFields?.homeroom?.on}
                      onChange={e => setBulkFields(prev => ({ ...prev, homeroom: { ...prev.homeroom, isHomeroom: e.target.checked } }))}
                    />
                  }
                  label="담임"
                />
                {bulkFields?.homeroom?.isHomeroom && (
                  <Box sx={{ display: 'flex', gap: 1, mt: 1 }}>
                    <FormControl fullWidth size="small">
                      <InputLabel>학년</InputLabel>
                      <Select
                        value={bulkFields?.homeroom?.grade || ''}
                        disabled={!bulkFields?.homeroom?.on}
                        label="학년"
                        onChange={e => setBulkFields(prev => ({ ...prev, homeroom: { ...prev.homeroom, grade: e.target.value } }))}
                      >
                        <MenuItem value="">학년</MenuItem>
                        <MenuItem value="1">1학년</MenuItem>
                        <MenuItem value="2">2학년</MenuItem>
                        <MenuItem value="3">3학년</MenuItem>
                      </Select>
                    </FormControl>
                    <TextField
                      label="반"
                      value={bulkFields?.homeroom?.classNo || ''}
                      disabled={!bulkFields?.homeroom?.on}
                      onChange={e => setBulkFields(prev => ({ ...prev, homeroom: { ...prev.homeroom, classNo: e.target.value } }))}
                      placeholder="반"
                      size="small"
                      sx={{ width: 100 }}
                    />
                  </Box>
                )}
              </Box>
            </Box>
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setBulkEditOpen(false)}>취소</Button>
          <Button onClick={saveBulkEdit} disabled={savingBulk} variant="contained">
            {savingBulk ? '저장 중...' : `${selectedUids.size}명 저장`}
          </Button>
        </DialogActions>
      </Dialog>

    </Box>
  )
}

const styles = {
  table: { width: '100%', borderCollapse: 'collapse' },
  th: { textAlign: 'left', padding: '0.6rem 0.8rem', backgroundColor: '#f0f0f0', fontSize: '0.85rem', fontWeight: 600 },
  td: { padding: '0.6rem 0.8rem', borderBottom: '1px solid #eee', fontSize: '0.9rem', verticalAlign: 'middle' },
  approveBtn: { padding: '0.3rem 0.75rem', backgroundColor: '#1a73e8', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontSize: '0.82rem' },
}
